Create README.md
radanalyticsio/base-notebook pull request #8
Opened 2017-05-05 10:30 UTC by willb

Fixes #6

2017-05-05 10:30 UTC, willb commented
@elmiko ptal

2017-05-17 21:56 UTC, elmiko requested changes
one minor nit, otherwise lgtm

2017-05-17 21:56 UTC, elmiko commented on README.md
> +This is a container image intended to make it easy to running Jupyter notebooks with Apache Spark on OpenShift.  You can use it as-is (by adding it to a project), or you can use it as the basis for a
s/to running/to run/

2017-07-07 19:44 UTC, willb commented
Thanks @elmiko!

2017-07-07 19:44 UTC, merged